version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local